# Site settings
title: Visit
subtitle: Novosibirsk
email: visitnovosibirsk@gmail.com
description: Novosibirsk is capital of Siberia with about 1.5 million residents. It's the fastest growing city in Russia, known for its prestigous arts, freezing temperatures and convienient location for tourist on the Trans-Siberian Railway, including train access to Russia, Kazakhstan, Mongolia, and China.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Novosibirsk
state: Siberia
zip_code: 55555
country: Russian Federation
phone: Coming soon

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
